export const INIT_CURRENCIES_START = "INIT_CURRENCIES_START";
export const SET_CURRENCIES = "SET_CURRENCIES";
export const INIT_CURRENCIES_FAIL = "INIT_CURRENCIES_FAIL";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const DELETE_ALL = "DELETE_ALL";
